version: '3.8'

services:
  sqlserver:
    image: mcr.microsoft.com/azure-sql-edge
    container_name: sqlserver-container
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=YourStrong!Passw0rd
    ports:
      - "1433:1433"

  myapp:
    build: .
    ports:
      - "6969:8080"
    depends_on:
      - sqlserver
  repositories:
    image: repositories
    build:
      context: .
      dockerfile: Repositories/Dockerfile
